// Mirrors the in-app policy (app repo: Domain/PrivacyPolicy.swift).
// Update both together — every claim must stay true to actual behavior.

export const EFFECTIVE_DATE = "August 31, 2026";
export const CONTACT_EMAIL = "dnage76@gmail.com";

export const POLICY_SECTIONS: { title: string; body: string }[] = [
  {
    title: "What happens to what you submit",
    body: "When you check a screenshot, photo, or pasted text, that content is sent over an encrypted connection to our server. Our server passes it to Google's Gemini AI service, which analyzes it and returns the assessment. Your content is used only to run that check. Our server does not store the screenshot or text after the check completes. Google processes it under its own API terms, which we do not control. Screenshots can contain personal information, so check only what you are comfortable sending.",
  },
  {
    title: "Deciding not to send",
    body: "The app asks before the first time it sends anything, and it never sends a check you have not confirmed. If you decline, the app stays installed and your saved history remains readable, but checks cannot run, because the analysis happens on the server. You can withdraw your agreement any time in Account, which makes the app ask again before the next check.",
  },
  {
    title: "What stays on your iPhone",
    body: "Your results and the content you checked are saved only on your iPhone, protected by iOS file protection. You can delete any single check, or everything at once from Account → Delete All History. The name you enter is stored only on your iPhone too.",
  },
  {
    title: "Deep Dive",
    body: "A Deep Dive sends the same screenshot to Google's Gemini service with web search enabled, so it can compare the content against current public reporting. Search queries are generated by that service from your content. The sources used are listed in the report.",
  },
  {
    title: "No account required",
    body: `The app uses a random, anonymous device key (stored in your iPhone's Keychain) to prevent abuse and enforce fair-use limits. On its own it is not connected to your name, email, or phone number. Our server keeps a record of the device (the key, your iPhone's vendor identifier, and the date and risk level of each check, never its content) so limits work across launches. To have that device record deleted, email ${CONTACT_EMAIL}.`,
  },
  {
    title: "If you choose to sign in",
    body: `Signing in is optional and everything works without it. If you do sign in with Apple or Google, our sign-in provider Clerk handles it and gives us your first name and the email address for the account. We show them in Account and use the name to greet you. This iPhone's device record is then linked to that account, so your checks and Deep Dives stay yours. Sign in with Apple can hide your real address behind a private relay if you prefer. You can delete the account from Account then Delete Account, which removes the account and its data and returns this iPhone to anonymous; your saved history on the iPhone is untouched.`,
  },
  {
    title: "Diagnostics",
    body: "The app records only fixed event names and error codes on your iPhone. Never your content, your screenshots, or your results. Our server records the date, endpoint, and IP address of requests that hit rate limits or fail validation, to stop abuse. Those abuse records are deleted after 90 days.",
  },
  {
    title: "No ads, no selling data",
    body: "We do not show ads, sell your information, or track you across other apps and websites.",
  },
  {
    title: "What we can't promise",
    body: "Smells Phishy points out warning signs. It cannot guarantee that any message is safe or fraudulent. Always verify important requests through an official source.",
  },
  {
    title: "Changes and contact",
    body: `If this policy changes, the app will tell you before the new version applies. Questions: ${CONTACT_EMAIL}. Effective ${EFFECTIVE_DATE}.`,
  },
];
